const claimApprovedData = {
	data: [
		{
			claimCode: 'YC001',
			contractCode: 'HD001',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 57244642,
			paymentMethod: 'guarantee',
			status: 'paid',
			requestedAt: '2023-11-22T00:00:00',
			processedAt: '2023-11-25T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC002',
			contractCode: 'HD002',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 56357011,
			paymentMethod: 'bank',
			status: 'paid',
			requestedAt: '2023-12-07T00:00:00',
			processedAt: '2023-12-13T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_2.pdf'],
		},
		{
			claimCode: 'YC003',
			contractCode: 'HD003',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm sức khỏe',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Đặng Văn Long',
			claimAmount: 11457624,
			paymentMethod: 'cash',
			status: 'processing',
			requestedAt: '2023-09-03T00:00:00',
			processedAt: '2023-09-11T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC004',
			contractCode: 'HD004',
			clientName: 'Lê Văn C',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Phan Hữu Thành',
			claimAmount: 67848114,
			paymentMethod: 'cash',
			status: 'processing',
			requestedAt: '2023-09-30T00:00:00',
			processedAt: '2023-10-02T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC005',
			contractCode: 'HD005',
			clientName: 'Trần Thị B',
			product: 'Bảo hiểm sức khỏe',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Đặng Văn Long',
			claimAmount: 95590972,
			paymentMethod: 'bank',
			status: 'paid',
			requestedAt: '2023-01-13T00:00:00',
			processedAt: '2023-01-22T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC006',
			contractCode: 'HD006',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Ngô Quang Huy',
			claimAmount: 99799118,
			paymentMethod: 'bank',
			status: 'processing',
			requestedAt: '2024-02-06T00:00:00',
			processedAt: '2024-02-10T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC007',
			contractCode: 'HD007',
			clientName: 'Phạm Thị D',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 17137282,
			paymentMethod: 'cash',
			status: 'paid',
			requestedAt: '2024-04-23T00:00:00',
			processedAt: '2024-04-27T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_7.pdf'],
		},
		{
			claimCode: 'YC008',
			contractCode: 'HD008',
			clientName: 'Phạm Thị D',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 85494061,
			paymentMethod: 'cash',
			status: 'processing',
			requestedAt: '2024-01-14T00:00:00',
			processedAt: '2024-01-19T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_8.pdf'],
		},
		{
			claimCode: 'YC009',
			contractCode: 'HD009',
			clientName: 'Lê Văn C',
			product: 'Bảo hiểm sức khỏe',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 82049835,
			paymentMethod: 'bank',
			status: 'processing',
			requestedAt: '2023-03-11T00:00:00',
			processedAt: '2023-03-17T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_9.pdf'],
		},
		{
			claimCode: 'YC010',
			contractCode: 'HD010',
			clientName: 'Trần Thị B',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 36563355,
			paymentMethod: 'guarantee',
			status: 'paid',
			requestedAt: '2024-02-04T00:00:00',
			processedAt: '2024-02-11T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_10.pdf'],
		},
		{
			claimCode: 'YC011',
			contractCode: 'HD011',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Phan Hữu Thành',
			claimAmount: 17986091,
			paymentMethod: 'bank',
			status: 'processing',
			requestedAt: '2023-11-25T00:00:00',
			processedAt: '2023-12-02T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_11.pdf'],
		},
		{
			claimCode: 'YC012',
			contractCode: 'HD012',
			clientName: 'Trần Thị B',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Ngô Quang Huy',
			claimAmount: 24361356,
			paymentMethod: 'cash',
			status: 'paid',
			requestedAt: '2024-01-28T00:00:00',
			processedAt: '2024-01-30T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC013',
			contractCode: 'HD013',
			clientName: 'Phạm Thị D',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Phan Hữu Thành',
			claimAmount: 61935857,
			paymentMethod: 'guarantee',
			status: 'paid',
			requestedAt: '2023-09-07T00:00:00',
			processedAt: '2023-09-10T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_13.pdf'],
		},
		{
			claimCode: 'YC014',
			contractCode: 'HD014',
			clientName: 'Trần Thị B',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Ngô Quang Huy',
			claimAmount: 96597333,
			paymentMethod: 'bank',
			status: 'processing',
			requestedAt: '2024-01-14T00:00:00',
			processedAt: '2024-01-24T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_14.pdf'],
		},
		{
			claimCode: 'YC015',
			contractCode: 'HD015',
			clientName: 'Đỗ Văn E',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 22704292,
			paymentMethod: 'guarantee',
			status: 'paid',
			requestedAt: '2023-06-19T00:00:00',
			processedAt: '2023-06-23T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_15.pdf'],
		},
		{
			claimCode: 'YC016',
			contractCode: 'HD016',
			clientName: 'Lê Văn C',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 83929981,
			paymentMethod: 'bank',
			status: 'paid',
			requestedAt: '2024-03-30T00:00:00',
			processedAt: '2024-04-06T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_16.pdf'],
		},
		{
			claimCode: 'YC017',
			contractCode: 'HD017',
			clientName: 'Lê Văn C',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Hưng Thịnh',
			processedBy: 'Phan Hữu Thành',
			claimAmount: 93677398,
			paymentMethod: 'guarantee',
			status: 'processing',
			requestedAt: '2023-02-10T00:00:00',
			processedAt: '2023-02-16T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_17.pdf'],
		},
		{
			claimCode: 'YC018',
			contractCode: 'HD018',
			clientName: 'Phạm Thị D',
			product: 'Bảo hiểm sức khỏe',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Ngô Quang Huy',
			claimAmount: 25961783,
			paymentMethod: 'cash',
			status: 'processing',
			requestedAt: '2023-10-16T00:00:00',
			processedAt: '2023-10-22T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC019',
			contractCode: 'HD019',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý An Phát',
			processedBy: 'Ngô Quang Huy',
			claimAmount: 98924772,
			paymentMethod: 'bank',
			status: 'processing',
			requestedAt: '2023-08-26T00:00:00',
			processedAt: '2023-09-05T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: [],
		},
		{
			claimCode: 'YC020',
			contractCode: 'HD020',
			clientName: 'Nguyễn Văn A',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý Minh Tâm',
			processedBy: 'Trịnh Thị Hoa',
			claimAmount: 90732009,
			paymentMethod: 'cash',
			status: 'paid',
			requestedAt: '2024-02-11T00:00:00',
			processedAt: '2024-02-13T00:00:00',
			note: 'Hồ sơ hợp lệ, đã xác minh chứng từ.',
			attachments: ['https://example.com/docs/claim_20.pdf'],
		},
	],
	page: 1,
	total: 20,
};

export default claimApprovedData;
