const rejectedClaims = {
	data: [
		{
			id: 'CR001',
			contractCode: 'HD001',
			clientName: 'Nguyen Van A',
			product: 'Bảo hiểm tai nạn cá nhân',
			agencyName: 'Đại lý Hưng Thịnh',
			claimAmount: 50000000,
			rejectionReason: 'Không đủ bằng chứng sự kiện bảo hiểm',
			reviewedBy: 'Trần Minh Quân',
			status: 'rejected',
			updatedAt: '2024-04-12T10:30:00',
		},
		{
			id: 'CR002',
			contractCode: 'HD002',
			clientName: 'Trần Thị B',
			product: 'Bảo hiểm ô tô',
			agencyName: 'Đại lý An Phát',
			claimAmount: 85000000,
			rejectionReason: 'Thiếu hồ sơ bệnh viện',
			reviewedBy: 'Nguyễn Thành Đạt',
			status: 'rejected',
			updatedAt: '2024-03-18T14:15:00',
		},
		{
			id: 'CR003',
			contractCode: 'HD003',
			clientName: 'Lê Văn C',
			product: 'Bảo hiểm sức khỏe toàn diện',
			agencyName: 'Đại lý Minh Tâm',
			claimAmount: 20000000,
			rejectionReason: 'Sự kiện không thuộc phạm vi bảo hiểm',
			reviewedBy: 'Lê Quỳnh Anh',
			status: 'rejected',
			updatedAt: '2024-05-01T09:00:00',
		},
		{
			id: 'CR004',
			contractCode: 'HD004',
			clientName: 'Phạm Văn D',
			product: 'Bảo hiểm du lịch',
			agencyName: 'Đại lý Hồng Phát',
			claimAmount: 3000000,
			rejectionReason: 'Khai báo thông tin sai lệch',
			reviewedBy: 'Nguyễn Văn An',
			status: 'rejected',
			updatedAt: '2024-02-10T08:20:00',
		},
		{
			id: 'CR005',
			contractCode: 'HD005',
			clientName: 'Hoàng Thị E',
			product: 'Bảo hiểm nhân thọ',
			agencyName: 'Đại lý An Khang',
			claimAmount: 100000000,
			rejectionReason: 'Không chứng minh được nguyên nhân tử vong',
			reviewedBy: 'Trương Minh Tâm',
			status: 'rejected',
			updatedAt: '2024-01-27T16:45:00',
		},
		{
			id: 'CR006',
			contractCode: 'HD006',
			clientName: 'Đặng Văn F',
			product: 'Bảo hiểm tai nạn nghề nghiệp',
			agencyName: 'Đại lý Gia Hưng',
			claimAmount: 15000000,
			rejectionReason: 'Tình huống không đủ điều kiện bồi thường',
			reviewedBy: 'Phạm Nhật Vũ',
			status: 'rejected',
			updatedAt: '2024-03-03T13:10:00',
		},
		{
			id: 'CR007',
			contractCode: 'HD007',
			clientName: 'Bùi Thị G',
			product: 'Bảo hiểm nhà ở',
			agencyName: 'Đại lý Thành Công',
			claimAmount: 45000000,
			rejectionReason: 'Hồ sơ xác minh thiếu chữ ký',
			reviewedBy: 'Lê Minh Trí',
			status: 'reviewing',
			updatedAt: '2024-05-28T11:50:00',
		},
		{
			id: 'CR008',
			contractCode: 'HD008',
			clientName: 'Ngô Văn H',
			product: 'Bảo hiểm xe máy',
			agencyName: 'Đại lý Bảo Hưng',
			claimAmount: 8000000,
			rejectionReason: 'Không có báo cáo từ cơ quan chức năng',
			reviewedBy: 'Đoàn Thị Kim',
			status: 'reviewing',
			updatedAt: '2024-05-29T17:00:00',
		},
		{
			id: 'CR009',
			contractCode: 'HD009',
			clientName: 'Lý Thị I',
			product: 'Bảo hiểm y tế cá nhân',
			agencyName: 'Đại lý Bình Minh',
			claimAmount: 25000000,
			rejectionReason: 'Khách hàng chưa đủ thời gian chờ',
			reviewedBy: 'Nguyễn Hoàng Sơn',
			status: 'rejected',
			updatedAt: '2024-04-20T12:30:00',
		},
		{
			id: 'CR010',
			contractCode: 'HD010',
			clientName: 'Tô Văn K',
			product: 'Bảo hiểm tài sản',
			agencyName: 'Đại lý Minh Phú',
			claimAmount: 92000000,
			rejectionReason: 'Không có bằng chứng tài sản bị thiệt hại',
			reviewedBy: 'Phan Hữu Tín',
			status: 'rejected',
			updatedAt: '2024-02-05T10:10:00',
		},
	],
	page: 1,
	total: 10,
};

export default rejectedClaims;
